# 01. Data Sourcing - Pandas

## 01.1. Importação das bibliotecas

### 01.1.1. Importando as bibliotecas nativas do Python

In [1]:
import sys

### 01.1.2. Importando as bibliotecas de terceiros

In [2]:
import pandas as pd

### 01.1.3. Importando os módulos locais do projeto

In [3]:
sys.path.append('..')
import params.consts as consts

## 01.2. Fontes dos dados

### 01.2.1. Listando as fontes dos dados

| Fonte de Dados           | Disponibilidade  | Formato              |
|--------------------------|------------------|----------------------|
| Data Lakes               | -                | -                    |
| Data Warehouses          | -                | -                    |
| Clouds                   | -                | -                    |
| Bancos de Dados SQL      | -                | -                    |
| Bancos de Dados NoSQL    | -                | -                    |
| APIs                     | -                | -                    |
| ERPs                     | -                | -                    |
| CRMs                     | -                | -                    |
| Web Scraping             | -                | -                    |
| Sistemas Empresariais    | Ok               | Csv                  |
| Dados Locais             | Ok               | Csv                  |
| Outros                   | -                | -                    |

## 01.3. União entre tabelas

### 01.3.1. Habilitando a exibição de todas as colunas

In [4]:
pd.set_option('display.max_columns', None)

### 01.3.2. Entendendo as tabelas e seus tipos de dados

In [5]:
dim_customers = pd.read_csv(consts.DIM_CUSTOMERS_RAW)

dim_calender = pd.read_csv(consts.DIM_CALENDER_RAW, sep = ';')

In [6]:
dim_customers.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0

In [7]:
dim_calender.head(5)

,Data,Ano,Mês,Nome do Mês,Dia,Dia da Semana,Dia Útil,Semana,CW,Trimestre,Nome do Trimestre,Semestre,Nome do Semestre,Início do Mês,Mês/Ano,Mês/Ano Curto
0,2000-01-01,2000,1,Janeiro,1,Sábado,Final de Semana,1,01/00,1,Trim 1,1,Semestre 1,2000-01-01,jan/00,jan/00
1,2000-01-02,2000,1,Janeiro,2,Domingo,Final de Semana,2,02/00,1,Trim 1,1,Semestre 1,2000-01-01,jan/00,jan/00
2,2000-01-03,2000,1,Janeiro,3,Segunda-Feira,Dia Útil,2,02/00,1,Trim 1,1,Semestre 1,2000-01-01,jan/00,jan/00
3,2000-01-04,2000,1,Janeiro,4,Terça-Feira,Dia Útil,2,02/00,1,Trim 1,1,Semestre 1,2000-01-01,jan/00,jan/00
4,2000-01-05,2000,1,Janeiro,5,Quarta-Feira,Dia Útil,2,02/00,1,Trim 1,1,Semestre 1,2000-01-01,jan/00,jan/00

In [8]:
dim_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [9]:
dim_calender.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25933 entries, 0 to 25932
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Data               25933 non-null  object
 1   Ano                25933 non-null  int64
 2   Mês                25933 non-null  int64
 3   Nome do Mês        25933 non-null  object
 4   Dia                25933 non-null  int64
 5   Dia da Semana      25933 non-null  object
 6   Dia Útil           25933 non-null  object
 7   Semana             25933 non-null  int64
 8   CW                 25933 non-null  object
 9   Trimestre          25933 non-null  int64
 10  Nome do Trimestre  25933 non-null  object
 11  Semestre           25933 non-null  int64
 12  Nome do Semestre   25933 non-null  object
 13  Início do Mês      25933 non-null  object
 14  Mês/Ano            25933 non-null  object
 15  Mês/Ano Curto      25933 non-null  object
dtypes: int64(6), object(10)
memory usage: 3.2+ MB

### 01.3.3. Unindo as tabelas

In [10]:
dim_customers['Dt_Customer'] = pd.to_datetime(dim_customers['Dt_Customer'])

dim_calender['Data'] = pd.to_datetime(dim_calender['Data'])

dataset_raw = dim_customers.merge(

    dim_calender[['Data', 'Mês', 'Trimestre']],

    left_on = 'Dt_Customer',

    right_on = 'Data',

    how = 'left'
    
)

dataset_raw = dataset_raw.drop(['Data'], axis = 1)

dataset_raw = dataset_raw.rename(columns = {
    'Mês': 'Dt_Customer_Month',
    'Trimestre': 'Dt_Customer_Quarter'
})

In [11]:
dataset_raw.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Dt_Customer_Month,Dt_Customer_Quarter
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1,9,3
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0,3,1
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0,8,3
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0,2,1
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0,1,1

In [12]:
dataset_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   datetime64[ns]
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
 29  Dt_Customer_Month    2240 non-null   int64
 30  Dt_Customer_Quarter  2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(27), object(2)
memory usage: 542.6+ KB

### 01.3.4. Salvando a tabela unificada

In [13]:
dataset_raw.to_csv(

    consts.DATASET_RAW_PANDAS,

    index = False

)

## 01.4. Compactação dos arquivos

### 01.4.1. Compactando arquivos brutos em csv usando o formato gzip

In [14]:
pd.read_csv(consts.DATASET_RAW_PANDAS).to_csv(
    
      consts.DATASET_RAW_COMPRESSED_PANDAS,

      index = False,

      compression = 'gzip',
      
)